<?php if (!isset($this->errorFlag) || $this->errorFlag === false): ?>

<!--fieldset>
    <div class="row-input">
        <label for="resource"><?php echo $this->_('Resource') ?></label>
        <input class="text" id="resource" type="text" name="resource" disabled="disabled" value="<?php echo $this->resource; ?>"/>
        <br class="clearall" />
    </div>
    <div class="row-input">
        <label for="appurl"><?php echo $this->_('Application URL') ?></label>
        <input class="text" id="appurl" type="text" name="appurl" />
        <br class="clearall" />
    </div>
</fieldset-->

<?php endif; ?>

